const api = window.cfpanel;
const state = { zones: [], tunnels: [], dns: [], selectedZoneId: "" };
const $ = (id) => document.getElementById(id);
const esc = (v) => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));

function unwrap(r){ if(!r?.ok) throw new Error(r?.error?.message || "Action failed"); return r.data; }
function toast(msg, bad=false){ const e=$("toast"); e.textContent=msg; e.classList.toggle("error",bad); e.hidden=false; clearTimeout(toast.t); toast.t=setTimeout(()=>e.hidden=true,4200); }
function connected(v){ $("connectionDot").classList.toggle("online",v); $("connectionText").textContent=v?"Cloudflare connected":"Not connected"; }
function nav(page){ document.querySelectorAll(".page").forEach(e=>e.classList.toggle("active",e.id===`page-${page}`)); document.querySelectorAll(".nav-item").forEach(e=>e.classList.toggle("active",e.dataset.page===page)); const m={dashboard:["Overview","Manage Cloudflare without living in the dashboard."],domains:["Domains & DNS","Manage zones and DNS records."],tunnels:["Zero Trust Tunnels","Create tunnels, publish hostnames and retrieve connector tokens."],settings:["Settings","Connect CFPanel to your Cloudflare account."]}[page]; $("pageTitle").textContent=m[0]; $("pageSubtitle").textContent=m[1]; }

async function refreshAll(){
  try{
    const settings=unwrap(await api.getSettings()); $("accountId").value=settings.accountId||"";
    if(!settings.hasToken){ connected(false); state.zones=[]; state.tunnels=[]; renderAll(); return; }
    unwrap(await api.verify()); connected(true);
    const [z,t]=await Promise.all([api.listZones(),api.listTunnels()]); state.zones=unwrap(z); state.tunnels=unwrap(t); renderAll();
    if(state.selectedZoneId) await loadDns(state.selectedZoneId);
  }catch(e){ connected(false); toast(e.message,true); renderAll(); }
}
async function loadDns(zoneId){ if(!zoneId){state.dns=[];renderDns();return;} try{state.dns=unwrap(await api.listDns(zoneId));renderDns();renderStats();}catch(e){toast(e.message,true);} }
function renderAll(){ renderZones(); renderDns(); renderDashboard(); renderStats(); renderTunnels(); }
function renderStats(){ $("statDomains").textContent=state.zones.length; $("statDns").textContent=state.selectedZoneId?state.dns.length:"—"; $("statTunnels").textContent=state.tunnels.length; $("statHealthy").textContent=state.tunnels.filter(t=>t.status==="healthy").length; }
function renderDashboard(){
  $("dashboardZones").className=state.zones.length?"stack":"stack empty-state"; $("dashboardZones").innerHTML=state.zones.length?state.zones.slice(0,6).map(z=>`<div class="list-row"><div><strong>${esc(z.name)}</strong><small>${esc(z.status||"unknown")}</small></div><span class="badge">${esc(z.type||"zone")}</span></div>`).join(""):"No domains loaded.";
  $("dashboardTunnels").className=state.tunnels.length?"stack":"stack empty-state"; $("dashboardTunnels").innerHTML=state.tunnels.length?state.tunnels.slice(0,6).map(t=>`<div class="list-row"><div><strong>${esc(t.name)}</strong><small>${esc(t.id)}</small></div><span class="badge ${esc(t.status)}">${esc(t.status||"unknown")}</span></div>`).join(""):"No tunnels loaded.";
}
function renderZones(){ const s=$("zoneSelect"),cur=state.selectedZoneId; s.innerHTML=`<option value="">Select a domain</option>${state.zones.map(z=>`<option value="${esc(z.id)}">${esc(z.name)}</option>`).join("")}`; if(state.zones.some(z=>z.id===cur))s.value=cur; else state.selectedZoneId=""; $("deleteZoneBtn").disabled=!state.selectedZoneId; $("newDnsBtn").disabled=!state.selectedZoneId; }
function renderDns(){
  const zone=state.zones.find(z=>z.id===state.selectedZoneId); $("dnsCaption").textContent=zone?`${state.dns.length} records for ${zone.name}`:"Choose a domain to view DNS."; $("deleteZoneBtn").disabled=!zone; $("newDnsBtn").disabled=!zone;
  if(!zone){$("dnsTable").innerHTML='<tr><td colspan="6" class="muted center">No domain selected.</td></tr>';return;}
  if(!state.dns.length){$("dnsTable").innerHTML='<tr><td colspan="6" class="muted center">No DNS records found.</td></tr>';return;}
  $("dnsTable").innerHTML=state.dns.map(r=>`<tr><td><span class="badge">${esc(r.type)}</span></td><td>${esc(r.name)}</td><td class="content-cell" title="${esc(r.content)}">${esc(r.content)}</td><td>${r.proxied===true?"Proxied":r.proxied===false?"DNS only":"—"}</td><td>${r.ttl===1?"Auto":esc(r.ttl)}</td><td><div class="row-actions"><button class="mini" data-dns-edit="${esc(r.id)}">Edit</button><button class="mini danger" data-dns-remove="${esc(r.id)}">Delete</button></div></td></tr>`).join("");
}
async function hostsFor(id){ try{const c=unwrap(await api.getTunnelConfig(id));return Array.isArray(c.ingress)?c.ingress.filter(r=>r.hostname):[];}catch{return [];} }
async function renderTunnels(){
  const g=$("tunnelGrid"); if(!state.tunnels.length){g.innerHTML='<article class="panel empty-state">No tunnels found.</article>';return;}
  const lists=await Promise.all(state.tunnels.map(t=>hostsFor(t.id)));
  g.innerHTML=state.tunnels.map((t,i)=>`<article class="tunnel-card"><div class="tunnel-top"><div><h3>${esc(t.name)}</h3><span class="badge ${esc(t.status)}">${esc(t.status||"unknown")}</span></div></div><code>${esc(t.id)}</code><div class="hostname-list">${lists[i].length?lists[i].map(h=>`<div class="hostname"><strong>${esc(h.hostname)}</strong><small>${esc(h.service)}</small><div class="tunnel-actions"><button class="mini danger" data-host-remove="${esc(t.id)}" data-hostname="${esc(h.hostname)}">Remove</button></div></div>`).join(""):'<div class="muted">No public hostnames configured.</div>'}</div><div class="tunnel-actions"><button class="mini" data-tunnel-host="${esc(t.id)}">Add hostname</button><button class="mini" data-tunnel-token="${esc(t.id)}">Connector token</button><button class="mini danger" data-tunnel-remove="${esc(t.id)}">Delete</button></div></article>`).join("");
}

function modal({title,body,submitText="Save",onSubmit,submit=true}){ $("modalTitle").textContent=title; $("modalBody").innerHTML=body; $("modalSubmit").textContent=submitText; $("modalSubmit").style.display=submit?"":"none"; const f=$("modalForm"); f.onsubmit=async ev=>{ev.preventDefault();if(!submit)return;try{$("modalSubmit").disabled=true;await onSubmit(new FormData(f));$("modal").close();}catch(e){toast(e.message,true);}finally{$("modalSubmit").disabled=false;}}; $("modal").showModal(); }
function dnsPayload(fd){ const type=String(fd.get("type")||"A"),r={type,name:String(fd.get("name")||"").trim(),content:String(fd.get("content")||"").trim(),ttl:Number(fd.get("ttl")||1)}; if(["A","AAAA","CNAME"].includes(type))r.proxied=fd.get("proxied")==="on"; if(type==="MX")r.priority=Number(fd.get("priority")||10); return r; }
function dnsModal(record){ const edit=!!record; modal({title:edit?"Edit DNS record":"Add DNS record",submitText:edit?"Update":"Create",body:`<div class="modal-fields"><div class="inline"><label><span>Type</span><select name="type">${["A","AAAA","CNAME","TXT","MX","SRV","CAA","NS"].map(t=>`<option ${record?.type===t?"selected":""}>${t}</option>`).join("")}</select></label><label><span>TTL</span><input name="ttl" type="number" min="1" value="${esc(record?.ttl||1)}"></label></div><label><span>Name</span><input name="name" required value="${esc(record?.name||"")}" placeholder="app.example.com"></label><label><span>Content / target</span><input name="content" required value="${esc(record?.content||"")}" placeholder="192.0.2.1 or target.example.com"></label><div class="inline"><label><span>MX priority</span><input name="priority" type="number" value="${esc(record?.priority||10)}"></label><label><span>Proxy</span><span><input name="proxied" type="checkbox" ${record?.proxied?"checked":""}> Enable Cloudflare proxy</span></label></div></div>`,onSubmit:async fd=>{const p=dnsPayload(fd); if(edit)unwrap(await api.updateDns(state.selectedZoneId,record.id,p));else unwrap(await api.createDns(state.selectedZoneId,p));await loadDns(state.selectedZoneId);toast(edit?"DNS record updated.":"DNS record created.");}}); }
function zoneModal(){ modal({title:"Add a domain",submitText:"Add to Cloudflare",body:'<div class="modal-fields"><label><span>Domain</span><input name="name" required placeholder="example.com"></label><p class="muted">Cloudflare will return the nameservers you need to set at your registrar.</p></div>',onSubmit:async fd=>{const z=unwrap(await api.createZone(fd.get("name")));toast(`${z.name} added.`);await refreshAll();state.selectedZoneId=z.id;renderZones();await loadDns(z.id);}}); }
function tunnelModal(){ modal({title:"Create Zero Trust tunnel",submitText:"Create tunnel",body:'<div class="modal-fields"><label><span>Tunnel name</span><input name="name" required placeholder="home-server"></label><p class="muted">Creates a remotely managed cloudflared tunnel.</p></div>',onSubmit:async fd=>{const t=unwrap(await api.createTunnel(fd.get("name")));toast(`${t.name} created.`);await refreshAll();showToken(t.id);}}); }
function hostModal(tunnelId){ modal({title:"Publish a hostname",submitText:"Publish",body:`<div class="modal-fields"><label><span>Domain</span><select name="zoneId" required>${state.zones.map(z=>`<option value="${esc(z.id)}">${esc(z.name)}</option>`).join("")}</select></label><label><span>Full hostname</span><input name="hostname" required placeholder="app.example.com"></label><label><span>Local service URL</span><input name="service" required placeholder="http://localhost:8080"></label><p class="muted">CFPanel updates tunnel ingress and its proxied CNAME together.</p></div>`,onSubmit:async fd=>{unwrap(await api.addPublicHostname({tunnelId,zoneId:fd.get("zoneId"),hostname:fd.get("hostname"),service:fd.get("service")}));toast("Public hostname published.");await refreshAll();}}); }
async function showToken(id){ try{const token=unwrap(await api.getTunnelToken(id)),w=`cloudflared.exe service install ${token}`,l=`sudo cloudflared service install ${token}`,d=`docker run -d --restart unless-stopped cloudflare/cloudflared:latest tunnel --no-autoupdate run --token ${token}`; modal({title:"Tunnel connector token",submit:false,body:`<p class="muted">Treat this token like a password. Anyone holding it can run this tunnel.</p><div class="codebox">${esc(token)}</div><div class="tunnel-actions"><button type="button" class="mini" data-copy="${esc(token)}">Copy token</button><button type="button" class="mini" data-copy="${esc(w)}">Copy Windows install</button><button type="button" class="mini" data-copy="${esc(l)}">Copy Linux install</button><button type="button" class="mini" data-copy="${esc(d)}">Copy Docker command</button></div>`});}catch(e){toast(e.message,true);} }

document.addEventListener("click",async ev=>{
  const n=ev.target.closest("[data-page]"); if(n)nav(n.dataset.page); const j=ev.target.closest("[data-jump]"); if(j)nav(j.dataset.jump); const c=ev.target.closest("[data-copy]"); if(c){await api.copy(c.dataset.copy);toast("Copied to clipboard.");}
  const edit=ev.target.closest("[data-dns-edit]")?.dataset.dnsEdit; if(edit){const r=state.dns.find(x=>x.id===edit);if(r)dnsModal(r);}
  const rd=ev.target.closest("[data-dns-remove]")?.dataset.dnsRemove; if(rd){const r=state.dns.find(x=>x.id===rd);if(r&&confirm(`Delete ${r.type} ${r.name}?`)){try{unwrap(await api.deleteDns(state.selectedZoneId,rd));await loadDns(state.selectedZoneId);toast("DNS record deleted.");}catch(e){toast(e.message,true);}}}
  const th=ev.target.closest("[data-tunnel-host]")?.dataset.tunnelHost; if(th)hostModal(th); const tt=ev.target.closest("[data-tunnel-token]")?.dataset.tunnelToken; if(tt)showToken(tt);
  const rh=ev.target.closest("[data-host-remove]"); if(rh){const tunnelId=rh.dataset.hostRemove,hostname=rh.dataset.hostname,zone=state.zones.filter(z=>hostname===z.name||hostname.endsWith(`.${z.name}`)).sort((a,b)=>b.name.length-a.name.length)[0]; if(!zone)toast("Could not match hostname to a loaded zone.",true); else if(confirm(`Remove ${hostname} and its matching tunnel CNAME?`)){try{unwrap(await api.removePublicHostname({tunnelId,zoneId:zone.id,hostname,removeDns:true}));await refreshAll();toast("Public hostname removed.");}catch(e){toast(e.message,true);}}}
  const rt=ev.target.closest("[data-tunnel-remove]")?.dataset.tunnelRemove; if(rt){const t=state.tunnels.find(x=>x.id===rt);if(t&&confirm(`Delete tunnel \"${t.name}\"?`)){try{unwrap(await api.deleteTunnel(rt));await refreshAll();toast("Tunnel deleted.");}catch(e){toast(e.message,true);}}}
});
$("zoneSelect").addEventListener("change",async ev=>{state.selectedZoneId=ev.target.value;renderZones();await loadDns(state.selectedZoneId);}); $("newZoneBtn").addEventListener("click",zoneModal); $("newDnsBtn").addEventListener("click",()=>dnsModal()); $("newTunnelBtn").addEventListener("click",tunnelModal); $("refreshBtn").addEventListener("click",refreshAll);
$("deleteZoneBtn").addEventListener("click",async()=>{const z=state.zones.find(x=>x.id===state.selectedZoneId);if(z&&confirm(`Delete ${z.name} from Cloudflare?`)){try{unwrap(await api.deleteZone(z.id));state.selectedZoneId="";state.dns=[];await refreshAll();toast("Domain deleted.");}catch(e){toast(e.message,true);}}});
$("settingsForm").addEventListener("submit",async ev=>{ev.preventDefault();try{unwrap(await api.saveSettings({accountId:$("accountId").value,apiToken:$("apiToken").value}));$("apiToken").value="";unwrap(await api.verify());toast("Cloudflare credentials saved and verified.");await refreshAll();}catch(e){toast(e.message,true);}});
$("clearTokenBtn").addEventListener("click",async()=>{if(confirm("Forget the saved Cloudflare API token?")){unwrap(await api.clearToken());$("apiToken").value="";connected(false);toast("Saved API token removed.");await refreshAll();}});
refreshAll();
